[
      {
        "ParameterKey": "KeyName",
        "ParameterValue": "ebsec2key"
      },    
      {
        "ParameterKey": "myVPC",
        "ParameterValue": "vpc-0d7f3ba450a86af3a"
      },
      {
        "ParameterKey": "PublicSubnet",
        "ParameterValue": "subnet-0b489775c192c55eb"
      },
      {
        "ParameterKey": "AMItoUse",
        "ParameterValue": "ami-0c02fb55956c7d316"
      }
]
